services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - ENV=dev
    volumes:
      - data:/app/backend/data
volumes:
  data: