name: Update OpenAPI Spec

on:
  schedule:
    - cron: "0 0 */3 * *" # every 3 days
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Start services
        run: docker compose up -d

      - name: Wait for docs endpoint
        run: pnpm wait-on http-get://127.0.0.1:8080/docs

      - name: Fetch OpenAPI spec
        run: curl http://127.0.0.1:8080/openapi.json | jq | tee docs/openapi.json

      - name: Fetch API version
        run: curl http://127.0.0.1:8080/api/version | jq | tee docs/version.json

      - name: Commit and push if openapi.json or version.json changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet docs/openapi.json docs/version.json; then
            git add docs/openapi.json docs/version.json
            git commit -m "chore: update docs [automated]"
            git push
          fi
